POST http://localhost:8080/revision/region-dev/25
Content-Type: application/json

{
    "submodules": {
        "https://github.com/infitx-org/profile-cd.git": {
            "path": "profiles/z-continuous-deployment",
            "ref": "c17383026e840c27659b2ce7c19e624688b99071"
        }
    }
}

###
POST http://localhost:8080/revision/region-dev/25
Content-Type: application/json

{
    "tests": {
        "gp_tests": {
            "totalAssertions": 5,
            "totalPassedAssertions": 5
        },
        "sdkFxSendE2EMin": {
            "totalAssertions": 7,
            "totalPassedAssertions": 7,
            "duration": 330055.161206,
            "report": "http://cephobjectstore.storage.ccdev.{{release-cd-domain}}/{{release-cd-bucket}}/6ebfe98bd54d758580dd1a2ea7f8ac675f48d2ae.txt"
        }
    }
}

###
POST http://localhost:8080/revision/mw-dev/1
Content-Type: application/json

{
    "submodules": {
        "https://github.com/infitx-org/profile-cd.git": {
            "path": "profiles/z-continuous-deployment",
            "ref": "71f3d4900a816b28832ffee9e53bc08ddb2a1f17"
        }
    },
    "tests": {
        "gp_tests": {
            "totalAssertions": 5,
            "totalPassedAssertions": 5
        }
    }
}

###
POST http://localhost:8080/revision/zm-dev/1
Content-Type: application/json

{
    "submodules": {
        "https://github.com/infitx-org/profile-cd.git": {
            "path": "profiles/z-continuous-deployment",
            "ref": "71f3d4900a816b28832ffee9e53bc08ddb2a1f17"
        },
        "comesa-buffer": {
            "path": "profiles/buffer",
            "ref": "main"
        }
    },
    "tests": {
        "gp_tests": {
            "totalAssertions": 5,
            "totalPassedAssertions": 5
        }
    }
}

###
GET http://localhost:8080/revision/region/1

###
GET http://localhost:8080/revision/mw/1

###
GET http://localhost:8080/revision/zm/1
