POST http://localhost:8080/revision/region-dev/2
Content-Type: application/json

{
    "submodules": {
        "https://github.com/infitx-org/profile-cd.git": {
            "ref": "94c4f2654efb4d7333df039170aca0e8a753a182"
        }
    }
}

###
POST http://localhost:8080/revision/region-dev/2
Content-Type: application/json

{
    "tests": {
        "gp_tests": {
            "totalAssertions": 5,
            "totalPassedAssertions": 5
        }
    }
}

###
POST http://localhost:8080/revision/mw-dev/2
Content-Type: application/json

{
    "submodules": {
        "https://github.com/infitx-org/profile-cd.git": {
            "ref": "94c4f2654efb4d7333df039170aca0e8a753a182"
        }
    },
    "tests": {
        "gp_tests": {
            "totalAssertions": 5,
            "totalPassedAssertions": 5
        }
    }
}

###
POST http://localhost:8080/revision/zm-dev/2
Content-Type: application/json

{
    "submodules": {
        "https://github.com/infitx-org/profile-cd.git": {
            "ref": "94c4f2654efb4d7333df039170aca0e8a753a182"
        },
        "comesa-buffer": {
            "ref": "main"
        }
    },
    "tests": {
        "gp_tests": {
            "totalAssertions": 5,
            "totalPassedAssertions": 5
        }
    }
}

###
GET http://localhost:8080/revision/region-dev/2

###
GET http://localhost:8080/revision/mw-dev/2

###
GET http://localhost:8080/revision/zm-dev/2

###
GET http://localhost:8080/release

###
GET http://localhost:8080/health
