ignore:
    - vulnerability: CVE-2023-45853
    - vulnerability: CVE-2023-5841
    - vulnerability: CVE-2023-6879
    - vulnerability: CVE-2025-21311
    - vulnerability: CVE-2025-7458
    - vulnerability: GHSA-cf4h-3jhx-xvhq
    - vulnerability: GHSA-fjxv-7rqg-78g4
    - vulnerability: CVE-2025-13836
    - vulnerability: CVE-2025-15467

# Set output format defaults
output:
    - 'table'
    - 'json'
